title: The General and the Actress
email: harry@harrylascelles.com
description: >- # this means to ignore newlines until "baseurl:"
  The lives and love of Francis Lascelles and Ann Catley.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.thegeneralandtheactress.com" # the base hostname & protocol for your site, e.g. http://example.com
markdown: kramdown

google_analytics: UA-141179634-1

plugins:
- jekyll-sitemap
- jekyll-seo-tag
